backend:
  name: github
  repo: AdrianDog840/engelstedsgade
  branch: main
  base_url: https://decapcms-auth.netlify.app

media_folder: "images"
public_folder: "/images"

collections:
  - name: "indhold"
    label: "Indhold"
    files:
      - name: "forside"
        label: "Forside"
        file: "_data/content.json"
        fields:
          - { label: "Hero overskrift", name: "hero_title", widget: "string" }
          - { label: "Hero underoverskrift", name: "hero_subtitle", widget: "string" }
          - { label: "Hero intro", name: "hero_intro", widget: "text" }
          - { label: "GF dato", name: "gf_date", widget: "string" }
          - { label: "GF type", name: "gf_type", widget: "string" }
          - { label: "CTA tekst", name: "cta_text", widget: "string" }
